services:
  # A Docker web service
  - type: main
    name: PROFESSOR-AUTOFILTER-V4.5
    env: python
    startCommand: python3 bot.py
    buildCommand: pip3 install -U -r requirements.txt
    repo: https://github.com/Cutozki/PROFESSOR-AUTOFILTER-V4.5.git # optional
    region: oregon # optional (defaults to oregon)
    plan: free # optional (defaults to starter)
    branch: web # optional (defaults to master)
    numInstances: 1 # optional (defaults to 1)
    healthCheckPath: /

#End of yaml
